export const patientsData = [
  {
    id: 1735673729504,
    name: "Juan Pérez",
    age: 29,
    photo: "https://via.placeholder.com/150?text=Juan+Pérez",
    diagnostic:
      "El asma requiere monitoreo constante para garantizar un manejo efectivo. Afecta significativamente la vida diaria y puede causar complicaciones si no se trata. Los chequeos médicos regulares son críticos para mantener el control y evitar episodios graves.",
    medicalHistory: {
      dob: "1995-06-15",
      gender: "Masculino",
      allergies: "Polvo",
      conditions: "Asma",
      medications: "Inhalador",
      height: 1.75,
      weight: 68.5,
      bloodType: "O+",
      emergencyContact: {
        name: "María López",
        relation: "Esposa",
        phone: "+1-123-456-7890",
      },
      vaccines: ["COVID-19", "Influenza", "Hepatitis B"],
      recentTests: ["Prueba de función pulmonar", "Radiografía de tórax"],
      lastVisit: "2024-12-15",
      doctorNotes:
        "El asma está bajo control. Continuar con la medicación prescrita.",
      lifestyle: {
        smoking: "No",
        alcohol: "Ocasionalmente",
        exercise: "Moderado",
      },
    },
  },
  {
    id: 1735673729505,
    name: "Ana Fernández",
    age: 43,
    photo: "https://via.placeholder.com/150?text=Ana+Fernández",
    diagnostic:
      "La hipertensión es una condición crónica que requiere ajustes en el estilo de vida y adherencia a la medicación. Puede derivar en problemas graves de salud si no se controla. Monitorear la presión arterial y mantener una rutina saludable son esenciales.",
    medicalHistory: {
      dob: "1981-03-24",
      gender: "Femenino",
      allergies: "Ninguna",
      conditions: "Hipertensión",
      medications: "Lisinopril",
      height: 1.65,
      weight: 72.3,
      bloodType: "A+",
      emergencyContact: {
        name: "Carlos Fernández",
        relation: "Hermano",
        phone: "+1-987-654-3210",
      },
      vaccines: ["COVID-19", "Tétanos", "Hepatitis A"],
      recentTests: ["Monitoreo de presión arterial", "Electrocardiograma"],
      lastVisit: "2024-11-10",
      doctorNotes:
        "La presión arterial está estable. Se recomienda una dieta baja en sodio.",
      lifestyle: { smoking: "No", alcohol: "Raramente", exercise: "Regular" },
    },
  },
  {
    id: 1735673729506,
    name: "Luis Martínez",
    age: 67,
    photo: "https://via.placeholder.com/150?text=Luis+Martínez",
    diagnostic:
      "La diabetes requiere un manejo estricto para prevenir complicaciones. Una dieta saludable, ejercicio regular y cumplir con la medicación son clave para mantener los niveles de azúcar en sangre. Los chequeos constantes son necesarios para ajustar los tratamientos según sea necesario.",
    medicalHistory: {
      dob: "1957-11-12",
      gender: "Masculino",
      allergies: "Maní",
      conditions: "Diabetes",
      medications: "Metformina",
      height: 1.78,
      weight: 85.0,
      bloodType: "B+",
      emergencyContact: {
        name: "Carmen Martínez",
        relation: "Esposa",
        phone: "+1-456-789-1234",
      },
      vaccines: ["COVID-19", "Influenza", "Hepatitis B"],
      recentTests: ["Prueba de azúcar en sangre", "Análisis de hemoglobina"],
      lastVisit: "2024-10-05",
      doctorNotes:
        "La diabetes está controlada. Mantener la dieta recomendada.",
      lifestyle: { smoking: "No", alcohol: "Nunca", exercise: "Regular" },
    },
  },
  {
    id: 1735673729507,
    name: "María González",
    age: 35,
    photo: "https://via.placeholder.com/150?text=María+González",
    diagnostic:
      "El colesterol elevado requiere una dieta balanceada y ejercicio regular. Es fundamental realizar chequeos constantes para evitar complicaciones cardiovasculares.",
    medicalHistory: {
      dob: "1989-09-10",
      gender: "Femenino",
      allergies: "Mariscos",
      conditions: "Colesterol elevado",
      medications: "Atorvastatina",
      height: 1.62,
      weight: 60.5,
      bloodType: "AB-",
      emergencyContact: {
        name: "Jorge González",
        relation: "Hermano",
        phone: "+1-654-321-9876",
      },
      vaccines: ["COVID-19", "Hepatitis B", "Influenza"],
      recentTests: ["Lipidograma"],
      lastVisit: "2024-09-20",
      doctorNotes:
        "Recomendar dieta baja en grasas y realizar más actividad física.",
      lifestyle: { smoking: "No", alcohol: "Raramente", exercise: "Regular" },
    },
  },
  {
    id: 1735673729508,
    name: "Carlos Jiménez",
    age: 12,
    photo: "https://via.placeholder.com/150?text=Carlos+Jiménez",
    diagnostic:
      "El paciente presenta amigdalitis recurrente, lo que sugiere la posibilidad de un tratamiento quirúrgico. Se recomienda mantener el sistema inmune fuerte y evitar cambios bruscos de temperatura.",
    medicalHistory: {
      dob: "2012-08-25",
      gender: "Masculino",
      allergies: "Lácteos",
      conditions: "Amigdalitis recurrente",
      medications: "Antibióticos según indicación",
      height: 1.45,
      weight: 38.0,
      bloodType: "A-",
      emergencyContact: {
        name: "Laura Jiménez",
        relation: "Madre",
        phone: "+1-432-567-8901",
      },
      vaccines: ["COVID-19", "Sarampión", "Polio"],
      recentTests: ["Cultivo de garganta"],
      lastVisit: "2024-11-15",
      doctorNotes:
        "Amigdalitis tratada exitosamente. Evaluar posibilidad de amigdalectomía.",
      lifestyle: {
        smoking: "No aplica",
        alcohol: "No aplica",
        exercise: "Moderado (actividad física infantil)",
      },
    },
  },
  {
    id: 1735673729509,
    name: "Clara Rodríguez",
    age: 54,
    photo: "https://via.placeholder.com/150?text=Clara+Rodríguez",
    diagnostic:
      "La osteoporosis está avanzando, lo que requiere atención continua. Es crucial mantener una dieta rica en calcio y vitamina D, junto con ejercicio leve.",
    medicalHistory: {
      dob: "1970-02-14",
      gender: "Femenino",
      allergies: "Penicilina",
      conditions: "Osteoporosis",
      medications: "Alendronato",
      height: 1.6,
      weight: 56.0,
      bloodType: "B-",
      emergencyContact: {
        name: "Pedro Rodríguez",
        relation: "Esposo",
        phone: "+1-321-654-0987",
      },
      vaccines: ["COVID-19", "Influenza"],
      recentTests: ["Densitometría ósea"],
      lastVisit: "2024-12-01",
      doctorNotes:
        "Incrementar la ingesta de calcio y realizar ejercicios de bajo impacto.",
      lifestyle: { smoking: "No", alcohol: "Moderado", exercise: "Leve" },
    },
  },
  {
    id: 1735673729510,
    name: "Daniela Torres",
    age: 26,
    photo: "https://via.placeholder.com/150?text=Daniela+Torres",
    diagnostic:
      "La migraña crónica afecta su calidad de vida y requiere un tratamiento preventivo adecuado. Es esencial identificar desencadenantes y mantener un registro de episodios para ajustar la medicación.",
    medicalHistory: {
      dob: "1998-07-30",
      gender: "Femenino",
      allergies: "Chocolate",
      conditions: "Migraña crónica",
      medications: "Sumatriptán",
      height: 1.68,
      weight: 62.4,
      bloodType: "O-",
      emergencyContact: {
        name: "Laura Torres",
        relation: "Hermana",
        phone: "+1-987-123-4567",
      },
      vaccines: ["COVID-19", "Tétanos"],
      recentTests: ["Resonancia magnética", "Análisis de sangre"],
      lastVisit: "2024-10-18",
      doctorNotes:
        "Recomendar técnicas de relajación y ajustar la medicación según necesidad.",
      lifestyle: { smoking: "No", alcohol: "Moderado", exercise: "Regular" },
    },
  },
  {
    id: 1735673729511,
    name: "Andrés López",
    age: 19,
    photo: "https://via.placeholder.com/150?text=Andrés+López",
    diagnostic:
      "El paciente presenta una fractura de tibia que requiere inmovilización y fisioterapia posterior. Se recomienda seguir estrictamente las indicaciones médicas para garantizar una recuperación completa.",
    medicalHistory: {
      dob: "2005-01-21",
      gender: "Masculino",
      allergies: "Ninguna",
      conditions: "Fractura de tibia",
      medications: "Analgésicos según indicación",
      height: 1.82,
      weight: 74.0,
      bloodType: "A+",
      emergencyContact: {
        name: "Carlos López",
        relation: "Padre",
        phone: "+1-654-987-3210",
      },
      vaccines: ["COVID-19", "Sarampión", "Tétanos"],
      recentTests: ["Radiografía de pierna"],
      lastVisit: "2024-11-10",
      doctorNotes: "Fractura bien alineada. Programar fisioterapia en un mes.",
      lifestyle: {
        smoking: "No",
        alcohol: "No",
        exercise: "Suspendido temporalmente",
      },
    },
  },
  {
    id: 1735673729512,
    name: "Sofía Ramírez",
    age: 73,
    photo: "https://via.placeholder.com/150?text=Sofía+Ramírez",
    diagnostic:
      "La artrosis está avanzando, lo que limita la movilidad y causa dolor. Se recomienda tratamiento con analgésicos y ejercicios terapéuticos para mejorar la calidad de vida.",
    medicalHistory: {
      dob: "1951-04-12",
      gender: "Femenino",
      allergies: "Aspirina",
      conditions: "Artrosis",
      medications: "Ibuprofeno",
      height: 1.55,
      weight: 58.0,
      bloodType: "B+",
      emergencyContact: {
        name: "Lucía Ramírez",
        relation: "Hija",
        phone: "+1-789-654-1234",
      },
      vaccines: ["COVID-19", "Influenza"],
      recentTests: ["Radiografía de rodillas"],
      lastVisit: "2024-11-25",
      doctorNotes:
        "La movilidad se mantiene limitada. Continuar fisioterapia y aumentar la medicación si el dolor empeora.",
      lifestyle: { smoking: "No", alcohol: "No", exercise: "Leve (terapia)" },
    },
  },
  {
    id: 1735673729513,
    name: "Jorge Castillo",
    age: 40,
    photo: "https://via.placeholder.com/150?text=Jorge+Castillo",
    diagnostic:
      "La gastritis crónica requiere cambios en la dieta y medicación para reducir los síntomas. Evitar alimentos irritantes y realizar chequeos regulares es fundamental para prevenir complicaciones.",
    medicalHistory: {
      dob: "1984-11-03",
      gender: "Masculino",
      allergies: "Ninguna",
      conditions: "Gastritis crónica",
      medications: "Omeprazol",
      height: 1.8,
      weight: 76.5,
      bloodType: "O+",
      emergencyContact: {
        name: "Mariana Castillo",
        relation: "Esposa",
        phone: "+1-321-456-7890",
      },
      vaccines: ["COVID-19", "Tétanos"],
      recentTests: ["Endoscopía gástrica"],
      lastVisit: "2024-12-05",
      doctorNotes:
        "Mejoría notable en síntomas. Recomendado mantener dieta blanda.",
      lifestyle: {
        smoking: "No",
        alcohol: "Raramente",
        exercise: "Regular (moderado)",
      },
    },
  },
];
